[package]
name = "the-curator"
version = "0.1.0"
description = "The Curator - Two Birthdays, One Beautiful Story"
authors = ["Ankur Yadav"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
